name: Deploy to HuggingFace Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to HuggingFace
        run: |
          git remote add hf https://aakashshrestha:${{ secrets.HF_TOKEN}}@huggingface.co/spaces/aakashshrestha/scholar-api
          git push hf main --force
